### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by CodyChaSsE** [SmushyTaco/Expanded-Bow-Enchanting#4]
Client crashes when trying to add looting book into an Anvil.

**Comment by SmushyTaco** [comment]
Download the latest update this was fixed.

**Comment by CodyChaSsE** [comment]
Sorry i should have been more specific. I was using the latest one. I actually came back to check on a new one as i intended on messaging you prior about the old one. But yea, new one is still crashing for me.

**Comment by SmushyTaco** [comment]
> Sorry i should have been more specific. I was using the latest one. I actually came back to check on a new one as i intended on messaging you prior about the old one. But yea, new one is still crashing for me.

You haven't provided any crash log for me to debug the issue. Or any specifics. Was this on a single player world? A server? If a server was it installed on the server and client? Just the server? Just the client? I need all this information to properly assess the situation.
